[theme]
base="light"
primaryColor="#005CA9"            # Azul Caixa
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F4F7FC" # Cartões/containers
textColor="#1B1F23"
font="sans serif"

[browser]
gatherUsageStats = false